concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-shared-runner-1"
  url = "http://gitlab"
  clone_url = "http://gitlab"
  id = 1
  token = "${GITLAB_RUNNER_1_TOKEN}"
  token_obtained_at = 2022-09-10T23:03:56Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    network_mode = "docker_gitlab"
    privileged = false
    pull_policy = ["if-not-present"]
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
