default:
  image: 
    name: docker/compose:1.29.2
  before_script:
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - cron
      - projects
      - docker-compose.yml
  script: sh ./build.sh

test:
  stage: test
  script: docker-compose config

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: 
    - sh ./deploy-gitlab.sh