image: 
  name: docker/compose:1.26.2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - cron/*
      - projects/*
      - docker-compose.yml
  script: sh ./build.sh

test:
  stage: test
  script: docker-compose config

deploy:
  stage: deploy
  only:
  - master
  script: echo "stage deploy"