---
default:
  image: 
    name: docker/compose:1.29.2
  before_script:
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.11-alpine
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # - pip3 install jinja2-cli[yaml,toml,xml]==0.8.2
    - pip3 install Jinja2
  artifacts:
    paths:
      - cron
      - projects
      - docker-compose.yml
  script: python ./build.py

test:
  stage: test
  script: docker-compose config

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: 
    - sh ./deploy-gitlab.sh