---
default:
  before_script:
    # https://unix.stackexchange.com/a/417661
    - apk update && apk add openssh sshpass

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: python:3.11-alpine
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - pip3 install Jinja2
  artifacts:
    paths:
      - cron
      - projects
      - .yamllint
      - deploy.sh
      - deploy-gitlab.sh
      - docker-compose.yml
      - post-deploy.sh
  script: python ./build.py

lint yaml:
  stage: test
  image: sdesbure/yamllint
  dependencies: 
    - build
  variables:
    GIT_STRATEGY: none
  before_script:
    - yamllint --version
  script:
    - yamllint ./docker-compose.yml
    - yamllint ./projects

shell check:
  stage: test
  image: koalaman/shellcheck-alpine:stable
  dependencies: 
    - build
  variables:
    GIT_STRATEGY: none
  before_script:
    - shellcheck --version
  script:
    - shellcheck ./deploy.sh
    - shellcheck ./deploy-gitlab.sh
    - shellcheck ./post-deploy.sh
    - shellcheck ./cron/*
    - shellcheck ./projects/*

validate docker-compose:
  stage: test
  image: docker/compose:1.29.2
  dependencies: 
    - build
  variables:
    GIT_STRATEGY: none
  script: docker-compose config

deploy:
  stage: deploy
  dependencies: 
    - build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script: 
    - sh ./deploy-gitlab.sh
