version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:13.5.4-ce.0
    container_name: gitlab
    depends_on:
      - redis
      - postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = '${GITLAB_DB_USER}'
        gitlab_rails['db_password'] = '${GITLAB_DB_PASS}'
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlab'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url 'http://${SERVER_IPv4}:8083'
    ports:
      - 8083:8083
#      - 8444:443
#      - 22:22
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/gitlab/config:/etc/gitlab
      - ${CONFIGS}/gitlab/backup:/var/opt/gitlab/backups
    restart: unless-stopped

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    depends_on:
      - gitlab-registrator
    ports:
      - 8093:8093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/gitlab-runner:/etc/gitlab-runner
    restart: unless-stopped

  gitlab-registrator:
    container_name: gitlab-registrator
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/gitlab-runner:/etc/gitlab-runner
    command: |
      register
      --non-interactive
      --executor "docker"
      --docker-image alpine:latest
      --url "http://${SERVER_IPv4}:8083/"
      --registration-token "${GITLAB_RUNNER_TOKEN}"
      --description "docker-shared-runner-1"
      --tag-list "docker"
      --run-untagged="true"
      --locked="false"
      --access-level="not_protected"

  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/redis:/data