version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - postgresql
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - RUN_MODE=prod
      - DB_TYPE=postgres
      - DB_HOST=postgresql:5432
      - DB_NAME=gitea
      - DB_USER=${GITEA_DB_USER}
      - DB_PASSWD=${GITEA_DB_PASSWD}
      - DISABLE_SSH=true
 #     - ROOT_URL=${SERVER_IPv4}
 #     - HTTP_PORT=8082
      - DOMAIN=${SERVER_IPv4}
    ports:
      - 3000:3000
#      - 8082:8082
#      - 8444:443
#      - 22:22
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/gitea:/data
    restart: unless-stopped

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: jenkins
    user: root
    ports:
      - 8082:8080
#      - "8443:8443"
      - 50000:50000
    volumes:
      - ${CONFIGS}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
