version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.1.2
    depends_on:
      - cloudflared
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ServerIP=${SERVER_IPv4}
      - ServerIPv6=${SERVER_IPv6}
      - WEB_PORT=8081
      - WEBTHEME='default-dark'
      - WEBUIBOXEDLAYOUT='traditional'
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNSMASQ_LISTENING=all
      - DNS1='${SERVER_IPv4}#5054'
      - DNS2=''
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/pihole/pihole:/etc/pihole
      - ${CONFIGS}/pihole/dnsmasq.d:/etc/dnsmasq.d
    network_mode: host
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53
      - 443:443
      - 8081:8081
  
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DNS1='1.1.1.1'
      - DNS2='1.0.0.1'
      - PORT=5054
    network_mode: host
    ports:
      - 5054:5054
