version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:13.5.4-ce.0
    container_name: gitlab
    depends_on:
      - redis
      - postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = '${GITLAB_DB_USER}'
        gitlab_rails['db_password'] = '${GITLAB_DB_PASS}'
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        #external_url 'http://gitlabtest.muc'
    ports:
      - 8082:80
#      - 8444:443
#      - 22:22
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/gitlab/config:/etc/gitlab
      - ${CONFIGS}/gitlab/backup:/var/opt/gitlab/backups
    restart: unless-stopped

  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/redis:/data
