version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:${HA_VERSION}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: host
    ports:
      - 8123:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/homeassistant:/config
