version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=home.ekelschot.net
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/swag:/config
      - ./homeassistant.proxy:/config/nginx/proxy-confs/homeassistant.subdomain.conf #hacky, but works on my machine
    ports:
      - 8443:443
      - 8080:80
    restart: unless-stopped
