version: "3"
services:
  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOWNLOADS}:/downloads # downloads folder
      - ${CONFIGS}/deluge:/config # config files
    network_mode: host
    ports:
      - 8112:8112
  
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGS}/plex/db:/config # plex database
      - ${CONFIGS}/plex/transcode:/transcode # temp transcoded files
      - ${MEDIA}/Movies:/movies
      - ${MEDIA}/Series:/series
    network_mode: host
    ports:
      - 32400:32400

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOADS}/torrents:/torrents # place where to put .torrent files for manual download
      - ${CONFIGS}:/config # config files (Jackett is appended)
    network_mode: host
    ports:
      - 9117:9117
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/sonarr:/config # config files
      - ${MEDIA}/Series:/series # tv shows folder
      - ${DOWNLOADS}:/downloads # download folder
    network_mode: host
    ports:
      - 8989:8989
  
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/radarr:/config # config files
      - ${MEDIA}/Movies:/movies # movies folder
      - ${DOWNLOADS}:/downloads # download folder
    network_mode: host
    ports:
      - 7878:7878
  
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIGS}/bazarr:/config # config files
      - ${MEDIA}/Movies:/movies # movies folder
      - ${MEDIA}/Series:/series # tv shows folder
    network_mode: host
    ports:
      - 6767:6767