version: "3"
services:
  postgresql:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - 5433:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/postgresql:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U someuser"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports: 
      - 5050:5050
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGS}/pgadmin:/var/lib/pgadmin
