---
http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true

    internal-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.1.0.0/24"
          - "10.2.0.0/24"
          - "10.3.0.0/24"
          - "10.5.0.0/24"

    security-headers:
      headers:
        accesscontrolallowmethods: GET, OPTIONS, PUT, POST
        accesscontrolmaxage: 100
        addvaryheader: true
        stsseconds: 63072000
        stspreload: true
        forcestsheader: true
        referrerpolicy: same-origin
        permissionsPolicy: "interest-cohort=(), geolocation=(), camera=(), microphone=(), payment=(), usb=(), vr=()"

    remove-headers:
      headers:
        customresponseheaders:
          server: ''
          x-powered-by: ''

    default-internal:
      chain:
        middlewares:
          - waf@docker
          - internal-whitelist
          - default-headers

    default-external:
      chain:
        middlewares:
          - waf@docker
          - default-headers
          - security-headers
          - remove-headers
