providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml

api:
  insecure: true
  dashboard: true

entryPoints:
  internal:
    address: ":80"
    http:
      middlewares:
        - default-internal@file
  external:
    address: ":443"
    http:
      middlewares:
        - default-external@file

certificatesResolvers:
  letsencrypt:
    acme:
      email: {{ letsencrypt.email }}
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: {{ letsencrypt.provider }}

log:
  filePath: "/var/logs/traefik.log"
  level: INFO
  format: common

accessLog:
  filePath: "/var/logs/access.log"
  format: common
  fields:
    defaultMode: keep
    names:
      StartUTC: drop

experimental:
  plugins:
    traefik-modsecurity-plugin:
      moduleName: "github.com/acouvreur/traefik-modsecurity-plugin"
      version: "v1.2.1"
