registry-frontend:
  image: konradkleine/docker-registry-frontend:v2
  container_name: registry-frontend
  environment:
    - TZ=${TZ}
    - ENV_DOCKER_REGISTRY_HOST=${SERVER_IPv4}
    - ENV_DOCKER_REGISTRY_PORT=5002
  volumes:
    - /etc/localtime:/etc/localtime:ro
  restart: unless-stopped
  ports: 
    - 8080:80
