esphome:
  container_name: esphome
  image: esphome/esphome:{{ esphome_version }}
  restart: unless-stopped
  environment:
    - PUID={{ global.user_id }}
    - PGID={{ global.group_id }}
    - TZ={{ global.timezone }}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - {{ global.docker_volume }}/esphome:/config
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.esphome.entrypoints=internal"
    - "traefik.http.routers.esphome.rule=Host(`esphome.{{ global.server.domain }}`)"
    - "traefik.http.services.esphome.loadbalancer.server.port=6052"
