homeassistant:
  container_name: homeassistant
  image: homeassistant/home-assistant:${HA_VERSION}
  depends_on:
    - adguard
    - deconz
  restart: unless-stopped
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  network_mode: host
  ports:
    - 8123:8123
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${VOLUMES}/homeassistant:/config
  devices:
    - /dev/ttyUSB-RFLINK:/dev/rflink
  healthcheck:
    test: python -m homeassistant --config /config --script check_config && wget --no-verbose --tries=1 --spider http://localhost:8123
    interval: 15s
    timeout: 10s
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.hass.entrypoints=internal"
    - "traefik.http.routers.hass.rule=Host(`hass.${SERVER_NAME}`)"
    - "traefik.http.services.hass.loadbalancer.server.port=8123"
    #- "traefik.http.middlewares.hass-geoip.forwardauth.address=http://localhost:8000/?locations=NL;&ips=127.0.0.1,10.0.0.0/8,52.210.253.108,52.48.198.78,52.49.253.220"
    #- "traefik.http.routers.whoami.middlewares=hass-geoip@docker"
