homeassistant:
  container_name: homeassistant
  image: homeassistant/home-assistant:${HA_VERSION}
  depends_on:
    - adguard
    - deconz
  restart: unless-stopped
  environment:
    - PUID=${PUID}
    - PGID=${PGID}
    - TZ=${TZ}
  network_mode: host
  ports:
    - 8123:8123
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${VOLUMES}/homeassistant:/config
